openapi: 3.1.0
info:
  title: GY Accounts
  description: ''
  version: 1.0.0
tags:
  - name: Users
paths:
  /user/metadata:
    post:
      summary: Initialize and Sync Metadata
      deprecated: false
      description: Initializes and syncs user's metadata.
      tags:
        - Users
      parameters:
        - name: x-user-id
          in: header
          description: User UserID.
          required: true
          example: ''
          schema:
            type: string
        - name: x-api-key
          in: header
          description: Service API Key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User%20Metadata'
                description: User metadata.
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /user/transform/userId:
    post:
      summary: Transform ProfileID to UserID
      deprecated: false
      description: Transforms a ProfileID into a UserID.
      tags:
        - Users
      parameters:
        - name: x-api-key
          in: header
          description: Service API Key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              title: ''
              type: object
              properties:
                profileId:
                  type: string
                  format: uuid
                  description: ProfileID to be transformed.
              required:
                - profileId
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                description: UserID transformed from the given ProfileID.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
  /user/transform/profileId:
    post:
      summary: Transform UserID to ProfileID
      deprecated: false
      description: Transforms a UserID into a ProfileID.
      tags:
        - Users
      parameters:
        - name: x-api-key
          in: header
          description: Service API Key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              title: ''
              type: object
              properties:
                userId:
                  type: string
                  description: UserID to be transformed.
              required:
                - userId
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: Profile ID transformed from the given User ID.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
webhooks: {}
components:
  schemas:
    User Profile:
      type: object
      properties:
        username:
          type: string
          description: User username.
        id:
          type: string
          description: User ProfileID.
          format: uuid
        phoneNumber:
          type: string
          description: User phone number.
          pattern: ^\+\d{1,3}\s\d{4,14}$
        roles:
          type: array
          items:
            type: string
            enum:
              - COMMON
              - ADMIN
              - DEVELOPER
            default: COMMON
            description: User role.
          description: User roles.
        picture:
          type: string
          description: User profile picture.
          format: uri
          pattern: >-
            ^https:\/\/api\.gycoding\.com\/accounts\/user\/picture\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        email:
          type: string
          description: User email.
          format: email
          pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
        apiKey:
          type: string
          description: User API Key.
      required:
        - username
        - picture
        - phoneNumber
        - email
        - id
      description: User Profile object.
    User Metadata:
      type: object
      properties:
        profile:
          $ref: '#/components/schemas/User%20Profile'
          description: User Profile object.
      required:
        - profile
      description: User metadata object.
    Error Response:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.
        status:
          type: integer
          minimum: 100
          maximum: 600
          examples:
            - 200
            - 201
            - 204
            - 304
            - 400
            - 401
            - 403
            - 405
            - 409
            - 415
            - 418
            - 500
            - 501
          description: Error HTTP status.
        owner:
          type: string
          enum:
            - GYCODING
            - API_GATEWAY
          description: Error owner.
      required:
        - code
        - message
        - status
        - owner
      description: Error Response object.
  responses:
    Bad Request:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Bad Request:
              summary: Bad Request
              value:
                code: BAD_REQUEST
                message: The endpoint is malformed.
                status: 400
                owner: API_GATEWAY
    Forbidden:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Forbidden to Service:
              summary: Forbidden to Service
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: GYCODING
            Forbidden to API Gateway:
              summary: Forbidden to API Gateway
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: API_GATEWAY
    Internal Error:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Database Error:
              summary: Database Error
              value:
                code: DB_ERROR
                message: >-
                  An error with the database has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
            Auth Error from Service:
              summary: Auth Error from Service
              value:
                code: AUTH_ERROR
                message: >-
                  An error with the authentication service has occurred, sorry
                  for the inconvenience.
                status: 500
                owner: GYCODING
            Auth Error from API Gateway:
              summary: Auth Error from API Gateway
              value:
                code: AUTH_ERROR
                message: >-
                  An error with the authentication service has occurred, sorry
                  for the inconvenience.
                status: 500
                owner: API_GATEWAY
            Gateway Error:
              summary: Gateway Error
              value:
                code: GATEWAY_ERROR
                message: >-
                  An internal API Gateway error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: API_GATEWAY
            Server Error:
              summary: Server Error
              value:
                code: SERVER_ERROR
                message: >-
                  An internal server error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
    Method Not Allowed:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Method Not Allowed:
              summary: Method Not Allowed
              value:
                code: METHOD_NOT_ALLOWED
                message: Method used to access this resource is not allowed.
                status: 405
                owner: GYCODING
    Not Modified:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Resource Not Modified:
              summary: Resource Not Modified
              value:
                code: RESOURCE_NOT_MODIFIED
                message: >-
                  The resource could not be modified due to some internal
                  conflict or error.
                status: 304
                owner: GYCODING
    Unauthorized:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Invalid Login:
              summary: Invalid Login
              value:
                code: INVALID_LOGIN
                message: >-
                  Invalid login due to the non existance of the user or invalid
                  password.
                status: 401
                owner: GYCODING
            Unauthorized to Service:
              summary: Unauthorized to Service
              value:
                code: UNAUTHORIZED
                message: The user is not authorized to access this resource.
                status: 401
                owner: GYCODING
            Invalid Token:
              summary: Invalid Token
              value:
                code: INVALID_TOKEN
                message: The provided token is invalid, expired or not even present.
                status: 401
                owner: API_GATEWAY
            Invalid API Key:
              summary: Invalid API Key
              value:
                code: INVALID_API_KEY
                message: The API Key is malformed.
                status: 401
                owner: API_GATEWAY
    Not Found:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Token Not Found:
              summary: Token Not Found
              value:
                code: TOKEN_NOT_FOUND
                message: Authentication token was not found.
                status: 404
                owner: API_GATEWAY
            Resource Not Found:
              summary: Resource Not Found
              value:
                code: RESOURCE_NOT_FOUND
                message: This resource was not found.
                status: 404
                owner: GYCODING
  securitySchemes: {}
servers:
  - url: https://api.gycoding.com/accounts
    description: Production
security: []
