openapi: 3.1.0
info:
  title: GY Books
  description: ''
  version: 1.0.0
tags:
  - name: Books
  - name: Friends
  - name: Profile
  - name: Activity
  - name: Lists
  - name: Metadata
paths:
  /{id}/public:
    get:
      summary: Get Book (Public)
      deprecated: false
      description: Retrieves a book.
      tags:
        - Books
      parameters:
        - name: id
          in: path
          description: Book ID.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
                description: Book.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - DEVELOPER
        - ADMIN
  /{id}:
    get:
      summary: Get Book
      deprecated: false
      description: Retrieves a book while being authenticated for private information.
      tags:
        - Books
      parameters:
        - name: id
          in: path
          description: Book ID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
                description: Book.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - DEVELOPER
        - ADMIN
    patch:
      summary: Update Book
      deprecated: false
      description: Updates an existing Book.
      tags:
        - Books
      parameters:
        - name: id
          in: path
          description: Book ID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
              description: Book.
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
                description: Book.
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    delete:
      summary: Delete Book
      deprecated: false
      description: Removes an existing Book rating.
      tags:
        - Books
      parameters:
        - name: id
          in: path
          description: Book ID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /{profileId}/list:
    get:
      summary: List Books by User
      deprecated: false
      description: >-
        Lists all books marked by the user, aside from the state marked. This
        resource is paginated.
      tags:
        - Books
      parameters:
        - name: profileId
          in: path
          description: User ProfileID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          description: Page of the list.
          required: true
          example: 0
          schema:
            type: number
        - name: size
          in: query
          description: Page size.
          required: true
          example: 0
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                  description: Book.
                description: List of books.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /friends:
    get:
      summary: List Friends
      deprecated: false
      description: Lists User's friends on GY Books.
      tags:
        - Friends
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User%20Profile'
                  description: Friend's profile.
                description: List of friends' profiles.
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /friends/{profileId}:
    delete:
      summary: Remove Friend
      deprecated: false
      description: Removes a friend.
      tags:
        - Friends
      parameters:
        - name: profileId
          in: path
          description: User ProfileID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /friends/request:
    post:
      summary: Send Friend Request
      deprecated: false
      description: Sends a Friend Request for someone to either accept it or deny it.
      tags:
        - Friends
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  description: Profile ID of the user receiving this Friend Request.
                  format: uuid
              required:
                - to
              description: Friend Request Object.
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User%20Profile'
                description: User Profile.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '409':
          $ref: '#/components/responses/Conflict'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    get:
      summary: Get Friend Requests
      deprecated: false
      description: Listens to the active friend requests.
      tags:
        - Friends
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend%20Request'
                  description: Friend Request.
                description: List of Friend Requests.
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /friends/manage:
    post:
      summary: Manage Friend Request
      deprecated: false
      description: Manages an existing friend request by accepting or declining it.
      tags:
        - Friends
      parameters:
        - name: requestId
          in: query
          description: Friend Request ID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: Command to manage Friend Request.
                  enum:
                    - ACCEPT
                    - DENY
              required:
                - command
              description: Friend Request Management Object.
            example:
              command: ACCEPT
        required: true
      responses:
        '204':
          description: ''
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '409':
          $ref: '#/components/responses/Conflict'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles:
    get:
      summary: List Profiles
      deprecated: false
      description: >-
        Retrieves a list of users while being authenticated for extra info about
        friendship with those users.
      tags:
        - Profile
      parameters:
        - name: query
          in: query
          description: Query to find profiles.
          required: true
          example: toxyc
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User%20Profile'
                  description: Profile.
                description: List of profiles.
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/public:
    get:
      summary: List Profiles (Public)
      deprecated: false
      description: Retrieves a list of users without needing to be authenticated.
      tags:
        - Profile
      parameters:
        - name: query
          in: query
          description: Query to find profiles.
          required: true
          example: gfigu
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User%20Profile'
                  description: Profile.
                description: List of profiles.
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/{profileId}:
    get:
      summary: Get Profile
      deprecated: false
      description: Retrieves a user profile for GY Books.
      tags:
        - Profile
      parameters:
        - name: profileId
          in: path
          description: Profile ID.
          required: true
          example: e6b94363-d415-462d-9b0e-c5c4796fcbd9
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User%20Profile'
                description: Profile.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/{profileId}/public:
    get:
      summary: Get Profile (Public)
      deprecated: false
      description: Retrieves a user profile for GY Books.
      tags:
        - Profile
      parameters:
        - name: profileId
          in: path
          description: Profile ID.
          required: true
          example: e6b94363-d415-462d-9b0e-c5c4796fcbd9
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User%20Profile'
                description: Profile.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/biography:
    patch:
      summary: Update Biography
      deprecated: false
      description: Modifies the biography of a user profile.
      tags:
        - Profile
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                biography:
                  type: string
                  description: Biography.
              required:
                - biography
              description: Update Biography Object.
            example:
              biography: string
        required: true
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: 'null'
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/{profileId}/halloffame:
    get:
      summary: Get Hall of Fame
      deprecated: false
      description: Retrieves a user's Hall of Fame.
      tags:
        - Profile
      parameters:
        - name: profileId
          in: path
          description: Profile ID.
          required: true
          example: 93dcc507-c706-4ed9-841f-fe470bdbb7d6
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hall%20of%20Fame'
                description: Hall of Fame.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/halloffame/book:
    patch:
      summary: Add Book to Hall of Fame
      deprecated: false
      description: Adds a book to the Hall of Fame of a user.
      tags:
        - Profile
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bookId:
                  type: string
                  description: Book ID.
              required:
                - bookId
              description: Add Book to Hall of Fame Object.
            example:
              bookId: '386446'
        required: true
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: 'null'
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '409':
          $ref: '#/components/responses/Conflict'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/halloffame/book/{bookId}:
    delete:
      summary: Delete Book from Hall of Fame
      deprecated: false
      description: Removes a book from the Hall of Fame for a user.
      tags:
        - Profile
      parameters:
        - name: bookId
          in: path
          description: Book ID.
          required: true
          example: '386446'
          schema:
            type: string
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: 'null'
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /profiles/halloffame/quote:
    patch:
      summary: Set Quote to Hall of Fame
      deprecated: false
      description: Sets the quote on the Hall of Fame of a user.
      tags:
        - Profile
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quote:
                  type: string
                  description: Favourite Quote.
              description: Set Quote to Hall of Fame Object.
            example:
              quote: Test.
        required: true
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: 'null'
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /activity:
    get:
      summary: List Friends Activities
      deprecated: false
      description: Retrieves all the activities made by user's friends.
      tags:
        - Activity
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
                  description: Activity.
                description: List of activities.
          headers:
            X-HasNext:
              required: true
              description: >-
                Whether the paginated list still has more elements to show on
                further pages or not.
              schema:
                type: boolean
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    post:
      summary: Add Activity
      deprecated: false
      description: Saves an activity made by a user.
      tags:
        - Activity
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: Activity.
              $ref: '#/components/schemas/Activity'
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
                description: Activity.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    patch:
      summary: React to an Activity
      deprecated: false
      description: Reacts to an activity made by a user.
      tags:
        - Activity
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: Activity.
              $ref: '#/components/schemas/Activity'
            example:
              id: a0b51068-d6c4-408a-9141-a4be3f300367
              profileId: dfa0987b-f1dd-41df-987e-409e5231c9ff
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
                description: Activity.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /activity/{profileId}:
    get:
      summary: List Activities
      deprecated: false
      description: Retrieves all the activities made by a user.
      tags:
        - Activity
      parameters:
        - name: profileId
          in: path
          description: User ProfileID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
                  description: Activity.
                description: List of activities.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /lists:
    get:
      summary: List lists
      deprecated: false
      description: Retrieves all of the user's lists.
      tags:
        - Lists
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookList'
                  description: Book List.
                description: Book Lists.
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    post:
      summary: Create List
      deprecated: false
      description: Creates a list.
      tags:
        - Lists
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookList'
              description: Book List.
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
                description: Book List.
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '409':
          $ref: '#/components/responses/Conflict'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    patch:
      summary: Update List
      deprecated: false
      description: Updates a list.
      tags:
        - Lists
      parameters:
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookList'
              description: Book List.
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
                description: Book List.
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /lists/{id}:
    get:
      summary: Get list
      deprecated: false
      description: Retrieves a list.
      tags:
        - Lists
      parameters:
        - name: id
          in: path
          description: List ID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
                description: Book List.
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    delete:
      summary: Remove List
      deprecated: false
      description: Removes a list.
      tags:
        - Lists
      parameters:
        - name: id
          in: path
          description: List ID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /lists/{id}/books:
    post:
      summary: Save a Book
      deprecated: false
      description: Saves a book to an specific list.
      tags:
        - Lists
      parameters:
        - name: id
          in: path
          description: List ID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookListElement'
              description: Book List book.
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
                description: Book List.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    patch:
      summary: Update a Book
      deprecated: false
      description: Updates a book from a specific list.
      tags:
        - Lists
      parameters:
        - name: id
          in: path
          description: List ID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookListElement'
              description: Book List book.
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
                description: Book List.
          headers: {}
        '304':
          $ref: '#/components/responses/Not Modified'
          description: ''
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /lists/{id}/books/{bookId}:
    delete:
      summary: Remove a Book
      deprecated: false
      description: Removes a book from a specific list.
      tags:
        - Lists
      parameters:
        - name: id
          in: path
          description: List ID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: bookId
          in: path
          description: Book ID.
          required: true
          example: ''
          schema:
            type: string
        - name: Authorization
          in: header
          description: Authorization token or API key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '401':
          $ref: '#/components/responses/Unauthorized'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
  /metadata:
    post:
      summary: Initialize and Sync Metadata
      deprecated: false
      description: Initializes and syncs user's book metadata.
      tags:
        - Metadata
      parameters:
        - name: x-profile-id
          in: header
          description: User ProfileID.
          required: true
          example: ''
          schema:
            type: string
        - name: x-api-key
          in: header
          description: Service API Key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
    delete:
      summary: Remove Metadata
      deprecated: false
      description: Removes user's book metadata.
      tags:
        - Metadata
      parameters:
        - name: x-profile-id
          in: header
          description: User ProfileID.
          required: true
          example: ''
          schema:
            type: string
            format: uuid
        - name: x-api-key
          in: header
          description: Service API Key.
          required: true
          example: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
          headers: {}
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
webhooks: {}
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          description: Book ID.
        averageRating:
          type: number
          description: Book Avergate Rating.
        userData:
          description: Book read status.
          $ref: '#/components/schemas/Book%20User%20Data'
      required:
        - id
        - averageRating
    Book User Data:
      type: object
      properties:
        profileId:
          type: string
          format: uuid
          description: User Profile ID.
        status:
          type: string
          enum:
            - WANT_TO_READ
            - READING
            - READ
          description: User status regarding this book.
        rating:
          type: number
          maximum: 5
          minimum: 0
          description: User rating for this book.
        progress:
          type: number
          description: User progress on the book.
        startDate:
          type: string
          format: date
          description: When the user has started reading this book.
        endDate:
          type: string
          format: date
          description: When the user has finished reading this book.
        editionId:
          type: string
          description: User favourite edition ID.
        review:
          type: string
          description: User review on the book.
      required:
        - status
        - rating
        - startDate
        - endDate
        - profileId
        - progress
        - editionId
        - review
    User Profile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Profile ID.
        username:
          type: string
          description: User username.
        phoneNumber:
          type: string
          description: User phone number.
          pattern: ^\+\d{1,3}\s\d{4,14}$
        picture:
          type: string
          format: uri
          description: User profile picture.
        email:
          type: string
          format: email
          description: User email.
        isFriend:
          type: boolean
          description: Whether user is friend or not of the user requesting.
        biography:
          type: string
          description: User biography for GY Books.
        hallOfFame:
          $ref: '#/components/schemas/Hall%20of%20Fame'
          description: Hall of Fame.
        activity:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
            description: Activity.
          description: List of activities.
      required:
        - username
        - picture
        - phoneNumber
        - email
        - biography
        - hallOfFame
        - activity
        - id
      description: User Profile object.
    Hall of Fame:
      type: object
      properties:
        books:
          type: array
          items:
            type: string
          minItems: 0
          maxItems: 5
          uniqueItems: true
          description: List of books on the Hall of Fame.
        quote:
          type: string
          description: Quote for the Hall of Fame.
      description: Hall of Fame object.
      required:
        - books
        - quote
    Friend Request:
      type: object
      properties:
        id:
          type: string
          description: Friend Request ID.
        from:
          type: string
          description: Profile ID of the user who sent the friend request.
        to:
          type: string
          description: Profile ID of the user who receives the friend request.
      description: Friend Request Object.
      required:
        - id
        - from
        - to
    Activity:
      type: object
      properties:
        id:
          type: string
          description: Activity ID.
          format: uuid
        message:
          type: string
          description: Activity Message.
        profileId:
          type: string
          format: uuid
          description: Activity Profile ID.
        likes:
          type: array
          items:
            type: string
            description: Activity Like Profile ID.
            format: uuid
          description: Activity Likes.
      description: Activity object.
      required:
        - id
    BookList:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Book List ID.
        name:
          type: string
          description: Book List name.
        description:
          type: string
          description: Book List description.
        books:
          type: array
          items:
            description: Book List book.
            $ref: '#/components/schemas/BookListElement'
          description: Book List books.
      required:
        - name
        - description
        - books
      description: Book List.
    BookListElement:
      type: object
      properties:
        bookId:
          type: string
          description: Book List book ID.
        order:
          type: integer
          description: Book List book order.
      required:
        - bookId
        - order
      description: Book List book.
    Books Metadata:
      type: object
      properties:
        friends:
          type: array
          items:
            type: string
            format: uuid
            description: Profile ID of a friend.
          description: List of friends.
        hallOfFame:
          $ref: '#/components/schemas/Hall%20of%20Fame'
          description: Hall of Fame.
        activity:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
            description: Activity.
          description: List of activities.
        biography:
          type: string
          description: Profile Biography.
      required:
        - friends
        - hallOfFame
        - activity
        - biography
      description: Books Metadata Object.
    Error Response:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.
        status:
          type: number
          minimum: 100
          maximum: 600
          examples:
            - 200
            - 201
            - 204
            - 304
            - 400
            - 401
            - 403
            - 405
            - 409
            - 415
            - 418
            - 500
            - 501
          description: Error status.
        owner:
          type: string
          description: Error owner.
          enum:
            - GYCODING
            - API_GATEWAY
      required:
        - code
        - message
        - status
        - owner
      description: Error Response object.
  responses:
    Not Modified:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Not Modified
          examples:
            Book Not Modified:
              summary: Book Not Modified
              value:
                code: BOOK_NOT_MODIFIED
                message: Book could not be modified.
                status: 304
                owner: GYCODING
    Bad Request:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Bad Request
          examples:
            Bad Request:
              summary: Bad Request
              value:
                code: BAD_REQUEST
                message: The endpoint is malformed.
                status: 400
                owner: API_GATEWAY
            Hall of Fame Limit Reached:
              summary: Hall of Fame Limit Reached
              value:
                code: HALL_OF_FAME_LIMIT_REACHED
                message: >-
                  User has reached the maximum number of Hall of Fame entries
                  (5).
                status: 400
                owner: GYCODING
            Friend Request sent to self:
              summary: Friend Request sent to self
              value:
                code: FRIEND_REQUEST_TO_SELF
                message: Cannot send a friend request to oneself.
                status: 400
                owner: GYCODING
    Unauthorized:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Unauthorized
          examples:
            Invalid Login:
              summary: Invalid Login
              value:
                code: INVALID_LOGIN
                message: >-
                  Invalid login due to the non existance of the user or invalid
                  password.
                status: 401
                owner: GYCODING
            Invalid API Key:
              summary: Invalid API Key
              value:
                code: INVALID_API_KEY
                message: The API Key is malformed.
                status: 401
                owner: API_GATEWAY
            Unauthorized to Service:
              summary: Unauthorized to Service
              value:
                code: UNAUTHORIZED
                message: The user is not authorized to access this resource.
                status: 401
                owner: GYCODING
            Invalid Token:
              summary: Invalid Token
              value:
                code: INVALID_TOKEN
                message: The provided token is invalid, expired or not even present.
                status: 401
                owner: API_GATEWAY
    Forbidden:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Forbidden
          examples:
            Forbidden to Service:
              summary: Forbidden to Service
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: GYCODING
            Forbidden to API Gateway:
              summary: Forbidden to API Gateway
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: API_GATEWAY
    Not Found:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Not Found
          examples:
            Token Not Found:
              summary: Token Not Found
              value:
                code: TOKEN_NOT_FOUND
                message: Authentication token was not found.
                status: 404
                owner: API_GATEWAY
            Book Not Found:
              summary: Book Not Found
              value:
                code: BOOK_NOT_FOUND
                message: Book not found.
                status: 404
                owner: GYCODING
    Method Not Allowed:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Method Not Allowed
          examples:
            Method Not Allowed:
              summary: Method Not Allowed
              value:
                code: METHOD_NOT_ALLOWED
                message: Method used to access this resource is not allowed.
                status: 405
                owner: GYCODING
    Conflict:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Conflict
          examples:
            Book already exists on Hall of Fame:
              summary: Book already exists on Hall of Fame
              value:
                code: HALL_OF_FAME_BOOK_ALREADY_EXISTS
                message: Book already exists in the user's Hall of Fame.
                status: 409
                owner: GYCODING
            Friend Request already exists:
              summary: Friend Request already exists
              value:
                code: FRIEND_REQUEST_ALREADY_EXISTS
                message: A friend request between these users already exists.
                status: 409
                owner: GYCODING
            Users are already friends:
              summary: Users are already friends
              value:
                code: FRIEND_REQUEST_ALREADY_FRIENDS
                message: Users are already friends.
                status: 409
                owner: GYCODING
    Internal Error:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Internal Error
          examples:
            Database Error:
              summary: Database Error
              value:
                code: DB_ERROR
                message: >-
                  An error with the database has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
            Auth Error from API Gateway:
              summary: Auth Error from API Gateway
              value:
                code: AUTH_ERROR
                message: >-
                  An error with the authentication service has occurred, sorry
                  for the inconvenience.
                status: 500
                owner: API_GATEWAY
            Gateway Error:
              summary: Gateway Error
              value:
                code: GATEWAY_ERROR
                message: >-
                  An internal API Gateway error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: API_GATEWAY
            Server Error:
              summary: Server Error
              value:
                code: SERVER_ERROR
                message: >-
                  An internal server error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
    Not Implemented:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
            description: Not Implemented
          examples:
            Not Implemented:
              summary: Not Implemented
              value:
                code: NOT_IMPLEMENTED
                message: The resource is not implemented yet.
                status: 501
                owner: API_GATEWAY
  securitySchemes: {}
servers: []
security: []
