openapi: 3.1.0
info:
  title: Heralds of Chaos
  description: ''
  version: 1.0.0
tags:
  - name: Characters
  - name: Creatures
  - name: Items
  - name: Worlds
paths:
  /characters/{id}:
    get:
      summary: Get Character
      deprecated: false
      description: >-
        Retrieves a specific character from the whole universe of Heralds of
        Chaos.
      tags:
        - Characters
      parameters:
        - name: id
          in: path
          description: Character's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
                description: Character.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /characters/list:
    get:
      summary: List Characters
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the characters from the whole
        universe of Heralds of Chaos.
      tags:
        - Characters
      parameters:
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
                  description: Character.
                description: List of characters.
                uniqueItems: true
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /characters/page:
    get:
      summary: Page Characters
      deprecated: false
      description: >-
        Retrieves a paginated list of all the characters from the whole universe
        of Heralds of Chaos.
      tags:
        - Characters
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
                  description: Character.
                description: List of characters.
                uniqueItems: true
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /creatures/{id}:
    get:
      summary: Get Creature
      deprecated: false
      description: >-
        Retrieves a specific creature from the whole universe of Heralds of
        Chaos.
      tags:
        - Creatures
      parameters:
        - name: id
          in: path
          description: Creature's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Creature'
                description: Creature.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /creatures/list:
    get:
      summary: List Creatures
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the creatures from the whole
        universe of Heralds of Chaos.
      tags:
        - Creatures
      parameters:
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Creature'
                  description: Creature.
                description: List of creatures.
                uniqueItems: true
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /creatures/page:
    get:
      summary: Page Characters
      deprecated: false
      description: >-
        Retrieves a paginated list of all the creatures from the whole universe
        of Heralds of Chaos.
      tags:
        - Creatures
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Creature'
                  description: Creature.
                description: List of creatures.
                uniqueItems: true
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /items/{id}:
    get:
      summary: Get Item
      deprecated: false
      description: Retrieves a specific item from the whole universe of Heralds of Chaos.
      tags:
        - Items
      parameters:
        - name: id
          in: path
          description: Item's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
                description: Item.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /items/list:
    get:
      summary: List Items
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the items from the whole universe
        of Heralds of Chaos.
      tags:
        - Items
      parameters:
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
                  description: Item.
                description: List of items.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /items/page:
    get:
      summary: Page Items
      deprecated: false
      description: >-
        Retrieves a paginated list of all the items from the whole universe of
        Heralds of Chaos.
      tags:
        - Items
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
                  description: Item.
                description: List of items.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/{id}:
    get:
      summary: Get World
      deprecated: false
      description: Retrieves a specific world from the whole universe of Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: id
          in: path
          description: World's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/World'
                description: World.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/places/{id}:
    get:
      summary: Get Place
      deprecated: false
      description: Retrieves a specific place from the whole universe of Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: id
          in: path
          description: Place's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
                description: Place.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/list:
    get:
      summary: List Worlds
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the worlds from the whole universe
        of Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/World'
                  description: World.
                description: List of worlds.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/places/list:
    get:
      summary: List Places
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the places from the whole universe
        of Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
                  description: Place.
                description: List of places.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/places/{id}/list:
    get:
      summary: List Places by World
      deprecated: false
      description: >-
        Retrieves a non-paginated list of all the places inside a specific world
        from the whole universe of Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: id
          in: path
          description: World's identifier.
          required: true
          example: ''
          schema:
            type: string
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
                  description: Place.
                description: List of places.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/page:
    get:
      summary: Page Worlds
      deprecated: false
      description: >-
        Retrieves a paginated list of all the worlds from the whole universe of
        Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/World'
                  description: World.
                description: List of worlds.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
  /worlds/places/page:
    get:
      summary: Page Places
      deprecated: false
      description: >-
        Retrieves a paginated list of all the places from the whole universe of
        Heralds of Chaos.
      tags:
        - Worlds
      parameters:
        - name: page
          in: query
          description: Number of page.
          required: true
          example: 0
          schema:
            type: integer
        - name: size
          in: query
          description: Amount of elements to show on one page.
          required: true
          example: 0
          schema:
            type: integer
        - name: lang
          in: query
          description: Language selector.
          required: true
          example: ''
          schema:
            type: string
            enum:
              - es
              - en
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
                  description: Place.
                description: List of places.
          headers: {}
        '400':
          $ref: '#/components/responses/Bad Request'
          description: ''
        '403':
          $ref: '#/components/responses/Forbidden'
          description: ''
        '404':
          $ref: '#/components/responses/Not Found'
          description: ''
        '405':
          $ref: '#/components/responses/Method Not Allowed'
          description: ''
        '500':
          $ref: '#/components/responses/Internal Error'
          description: ''
      security: []
      x-roles:
        - COMMON
        - ADMIN
        - DEVELOPER
webhooks: {}
components:
  schemas:
    Item:
      type: object
      properties:
        identifier:
          type: string
          description: Item identifier.
        name:
          type: string
          description: Item name.
        description:
          type: string
          description: Item description.
        image:
          type: string
          format: uri
          description: Item image.
        type:
          type: string
          enum:
            - COMPLETE_ITEM
            - FRAGMENT
            - UNKNOWN
          description: Item type.
      required:
        - identifier
        - name
        - description
        - image
        - type
      description: Item object.
    Character:
      type: object
      properties:
        identifier:
          type: string
          description: Character identifier.
        name:
          type: string
          description: Character name.
        title:
          type: string
          description: Character title.
        description:
          type: string
          description: Character description.
        race:
          type: string
          description: Character race.
          enum:
            - Æsir
            - Valkyria
            - Elfo de Luz
            - Elfo Oscuro
            - Vanir
            - Humano
            - Vegar
            - Nibelungo
            - Gigante de Hielo
            - Gigante de Fuego
            - Entidad Primigenia
            - Desconocida
        image:
          type: string
          format: uri
          description: Character image.
        world:
          description: World where the character belongs.
          $ref: '#/components/schemas/World'
      required:
        - name
        - identifier
        - description
        - title
        - image
        - world
        - race
      description: Character object.
    World:
      type: object
      properties:
        identifier:
          type: string
          description: World identifier.
        name:
          type: string
          description: World name.
        description:
          type: string
          description: World description.
        places:
          type: array
          items:
            $ref: '#/components/schemas/Place'
          description: World places.
        image:
          type: string
          format: uri
          description: World image.
        detailedIcon:
          type: string
          format: uri
          description: World icon.
      required:
        - identifier
        - name
        - description
        - places
        - image
        - detailedIcon
      description: World object.
    Place:
      type: object
      properties:
        identifier:
          type: string
          description: Place identifier.
        name:
          type: string
          description: Place name.
        description:
          type: string
          description: Place description.
        image:
          type: string
          format: uri
          description: Place image.
      required:
        - identifier
        - name
        - description
        - image
      description: Place object.
    Creature:
      type: object
      properties:
        identifier:
          type: string
          description: Creature identifier.
        name:
          type: string
          description: Creature name.
        description:
          type: string
          description: Creature description.
        image:
          type: string
          format: uri
          description: Creature image.
      required:
        - identifier
        - name
        - description
        - image
      description: Creature object.
    Error Response:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.
        status:
          type: integer
          minimum: 100
          maximum: 600
          examples:
            - 200
            - 201
            - 204
            - 304
            - 400
            - 401
            - 403
            - 405
            - 409
            - 415
            - 418
            - 500
            - 501
          description: Error HTTP status.
        owner:
          type: string
          enum:
            - GYCODING
            - API_GATEWAY
          description: Error owner.
      required:
        - code
        - message
        - status
        - owner
      description: Error Response object.
  responses:
    Bad Request:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Bad Request:
              summary: Bad Request
              value:
                code: BAD_REQUEST
                message: The endpoint is malformed.
                status: 400
                owner: API_GATEWAY
    Forbidden:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Forbidden to Service:
              summary: Forbidden to Service
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: GYCODING
            Forbidden to API Gateway:
              summary: Forbidden to API Gateway
              value:
                code: FORBIDDEN
                message: The user has no permission to access this resource.
                status: 403
                owner: API_GATEWAY
    Not Found:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Token Not Found:
              summary: Token Not Found
              value:
                code: TOKEN_NOT_FOUND
                message: Authentication token was not found.
                status: 404
                owner: API_GATEWAY
            Resource Not Found:
              summary: Resource Not Found
              value:
                code: RESOURCE_NOT_FOUND
                message: This resource was not found.
                status: 404
                owner: GYCODING
    Method Not Allowed:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Method Not Allowed:
              summary: Method Not Allowed
              value:
                code: METHOD_NOT_ALLOWED
                message: Method used to access this resource is not allowed.
                status: 405
                owner: GYCODING
    Internal Error:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error%20Response'
          examples:
            Database Error:
              summary: Database Error
              value:
                code: DB_ERROR
                message: >-
                  An error with the database has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
            Auth Error from Service:
              summary: Auth Error from Service
              value:
                code: AUTH_ERROR
                message: >-
                  An error with the authentication service has occurred, sorry
                  for the inconvenience.
                status: 500
                owner: GYCODING
            Auth Error from API Gateway:
              summary: Auth Error from API Gateway
              value:
                code: AUTH_ERROR
                message: >-
                  An error with the authentication service has occurred, sorry
                  for the inconvenience.
                status: 500
                owner: API_GATEWAY
            Gateway Error:
              summary: Gateway Error
              value:
                code: GATEWAY_ERROR
                message: >-
                  An internal API Gateway error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: API_GATEWAY
            Server Error:
              summary: Server Error
              value:
                code: SERVER_ERROR
                message: >-
                  An internal server error has occurred, sorry for the
                  inconvenience.
                status: 500
                owner: GYCODING
  securitySchemes: {}
servers:
  - url: https://api.gycoding.com/heraldsofchaos
    description: Production
security: []
